examples : RS-422 command seq sample
sonydevworld/spresense pull request #489
Opened 2022-09-25 08:22 UTC by shino-ixy

Add Example for NextStep, For Spresense RS-422/485 AddOn Board.
This Program can select RD/DE pin from I2C_DIN/I2C_DOUT, EMMC2/EMMC3,
and use UART2 (115200bps).
- https://nextstep.official.ec/items/38434310

It's work look line here
- https://qiita.com/ixy-shino/items/e463c03d56b31ac5d0a7

I'm so happy you will review these codes in your coffee time.

2022-09-26 05:47 UTC, SPRESENSE requested changes
Please rebase and remove merge commit.

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> +
```suggestion

/****************************************************************************
 * Private Types
 ****************************************************************************/

```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> +  board_gpio_write(id, true);
```suggestion
  board_gpio_write(id, 1);
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> +  board_gpio_write(id, false);
```suggestion
  board_gpio_write(id, 0);
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> +          printf("Error : %s is not support argument.\n", argv[1]);
```suggestion
          printf("Error : %s is not supported.\n", argv[1]);
```
And, it is helpful to display the usage.

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @brief Data Write to ttyS2
```suggestion
 * @brief Data Write to ttySx
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param comm_tty file descriptor of ttyS2
```suggestion
 * @param comm_tty file descriptor of ttySx
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param comm_tty file descriptor of ttyS2
```suggestion
 * @brief Data Read from ttySx
 *
 * @param comm_tty file descriptor of ttySx
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @brief Command Read from ttyS2
```suggestion
 * @brief Command Write from ttySx
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param comm_tty file descriptor of ttyS2
```suggestion
 * @param comm_tty file descriptor of ttySx
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param cmd read command
```suggestion
 * @param cmd write command
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param comm_tty file descriptor of ttyS2
```suggestion
 * @brief Command Read from ttySx
 *
 * @param comm_tty file descriptor of ttySx
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param comm_tty ttyS2 filde descriptor
```suggestion
 * @param comm_tty ttySx file descriptor
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param comm_tty ttyS2 filde descriptor
```suggestion
 * @param comm_tty ttySx file descriptor
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param comm_tty ttyS2 filde descriptor
```suggestion
 * @param comm_tty ttySx file descriptor
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @brief RS-485 Message Pathing
```suggestion
 * @brief RS-485 Command Message Handshake
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param offset head of position
```suggestion
 * @param offset position from head
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param offset head of position
```suggestion
 * @param offset position from head
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param pget_cmd recv buffer
```suggestion
 * @param comm_tty file descriptor of ttySx
 * @param msg send message
 * @param len length of message
 * @param offset position from head
 * @param pget_cmd received command
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @brief RS-485 Message Pathing
```suggestion
 * @brief RS-485 Data Message Handshake
```

2022-09-26 05:47 UTC, SPRESENSE commented on examples/rs422/rs422_main.c
> + * @param pget_cmd recv buffer
```suggestion
 * @param comm_tty file descriptor of ttySx
 * @param len length of message
 * @param pbuf received message
```

2022-09-26 08:54 UTC, shino-ixy commented
Thank you for your review!!
I've just updated any issues.

2022-09-26 11:18 UTC, SPRESENSE commented
Several typos still remain and remove a merge commit.
s/filde descriptor/file descriptor/

2022-09-27 04:44 UTC, shino-ixy commented
Sorry, I broke my branch...
Reject pull request and Re-Open pull request.

2022-09-27 04:45 UTC, closed without merging

2022-10-11 07:24 UTC, shino-ixy commented
Thank you for reviewing. I’ve just updated any issues.