examples : add RS-422 sample
sonydevworld/spresense pull request #490
Opened 2022-09-27 04:46 UTC by shino-ixy

Add Example for NextStep, For Spresense RS-422/485 AddOn Board.
This Program can select RD/DE pin from I2C_DIN/I2C_DOUT, EMMC2/EMMC3,
and use UART2 (115200bps).

https://nextstep.official.ec/items/38434310
It's work look line here

https://qiita.com/ixy-shino/items/e463c03d56b31ac5d0a7
I'm so happy you will review these codes in your coffee time.

2022-09-27 04:48 UTC, shino-ixy commented
Please wait a moment, remove merge.

2022-09-27 04:59 UTC, shino-ixy commented
Thank you for waiting.
I've ready to merge for the pull request.

2022-09-28 11:24 UTC, SPRESENSE commented
@shino-ixy san, could you please add sdk/configs/examples/rs422/README.txt?
Thanks.

2022-09-29 10:08 UTC, shino-ixy commented
OK! I've just written README.txt, Is this content sufficient?

2022-09-29 10:53 UTC, SPRESENSE commented
@shino-ixy san
README.txt you added is very helpful. Thank you.

And, please refer to [README.txt](https://github.com/sonydevworld/spresense/blob/develop/sdk/configs/examples/alarm/README.txt), and add a simple README.txt under sdk/configs/examples/rs422 directory.

2022-10-11 22:45 UTC, shino-ixy commented
@SPRESENSE Thank you for checking, I've just added README in configs.

2022-10-12 00:41 UTC, SPRESENSE requested changes
@shino-ixy , please modify an example name as I suggested.

2022-10-12 00:41 UTC, SPRESENSE commented on sdk/configs/examples/rs422/README.txt
> +This configuration contains required options to use gyro example.
```suggestion
This configuration contains required options to use rs422 example.
```

2022-10-12 00:41 UTC, SPRESENSE commented on sdk/configs/examples/rs422/README.txt
> +examples/gyro
```suggestion
examples/rs422
```

2022-10-12 01:04 UTC, SPRESENSE approved these changes
@shino-ixy san, thank you!!

2022-10-12 01:05 UTC, merged